Update patch set 2
Patch Set 2: Code-Review-1

python vendor/cm/build/tools/repopick.py -t n_asb_04-2018

is broken when it reaches this patch:

Applying change number 211322...
--> Subject:       "libmediaplayerservice:Fix deadlock on gapless start failure"
--> Project path:  frameworks/av
--> Change number: 211322 (Patch Set 211322)
['git fetch github', u'refs/changes/22/211322/2']
From https://github.com/LineageOS/android_frameworks_av
 * branch                refs/changes/22/211322/2 -> FETCH_HEAD
error: could not apply 5ae13b7a4... libmediaplayerservice:Fix deadlock on gapless start failure
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
Recorded preimage for 'media/libmediaplayerservice/MediaPlayerService.cpp'
ERROR: git command failed
repopick failed, exiting...

Patch-set: 2
Reviewer: seven rock <15908@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Code-Review=-1