Update patch set 1
Patch Set 1: Code-Review-1

(1 comment)

This patch introduces a build error for the skyrocket (msm8660) device: 

frameworks/av/media/libstagefright/AwesomePlayer.cpp:243:5: error: 'mDelayedInitialization' was not declared in this scope

Patch-set: 1