Update patch set 2
Patch Set 2:

FYI - hammerhead builds have been broken for a few days (incl nightlies).  Haven't had a chance to look into it so I'm not sure exactly which av related commit broke it.


frameworks/av/media/libstagefright/ExtendedCodec.cpp: In static member function 'static android::status_t android::ExtendedCodec::updatePcmOutputFormat(const android::sp<android::MetaData>&, android::sp<android::IOMX>, android::IOMX::node_id, const char*)':
frameworks/av/media/libstagefright/ExtendedCodec.cpp:1432:29: error: 'InitOMXParams' was not declared in this scope
ESC[32mtarget asm:ESC[0m libvpx <= /store3/cm-11.0/out/target/product/hammerhead/obj/STATIC_LIBRARIES/libvpx_intermediates/vp8/common/arm/neon/dequant_idct_neon.asm.s
make: *** [/store3/cm-11.0/out/target/product/hammerhead/obj/SHARED_LIBRARIES/libstagefright_intermediates/ExtendedCodec.o] Error 1
make: *** Waiting for unfinished jobs....
frameworks/av/media/libstagefright/OMXCodec.cpp: In member function 'android::status_t android::OMXCodec::allocateBuffersOnPort(OMX_U32)':
frameworks/av/media/libstagefright/OMXCodec.cpp:2119:9: error: 'ExtendedCodec' has not been declared
make: *** [/store3/cm-11.0/out/target/product/hammerhead/obj/SHARED_LIBRARIES/libstagefright_intermediates/OMXCodec.o] Error 1

Patch-set: 2
Reviewer: Sam Mortimer <3075@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Verified=0