[C++23] mediametrics: Add missing header
Fixes build failures with C++23 by adding explicit includes
for standard library components that are no longer transitively
included. Specifically, adds queue to MediaMetricsService.h

Error:
frameworks/av/services/mediametrics/MediaMetricsService.cpp:178:38:
error: implicit instantiation of undefined template 'std::queue<int>'
  178 | std::queue<int> MediaMetricsService::sCachedUids;

Generated by Gemini.

Flag: EXEMPT PURE_REFACTOR
Bug: 429048222
Test: m libmediametricsservice
Change-Id: I8f652381210dd436df3137bd6751f60c398d5cd5