Update patch set 1
Patch Set 1:

Breaks build on tilapia.

frameworks/av/services/audioflinger/Threads.cpp: In member function 'virtual bool android::AudioFlinger::PlaybackThread::threadLoop()':
frameworks/av/services/audioflinger/Threads.cpp:2064:55: error: 'class android::AudioFlinger' has no member named 'mLPAEffectChain'

Patch-set: 1