liberror: Add logs for failed conversions/status checks
Add error logs for macros, if the conversions,
status checks fail, as in error case these macros
cause methods to exit/return without indicating
the potential errors.

Bug: 308706390
Test: build source tree

Change-Id: I608fbb0ece4b085ce9455e5a603bf4cdb07cf0cb
Merged-In: I608fbb0ece4b085ce9455e5a603bf4cdb07cf0cb