Fix overloaded virtual function warning
Clang warns:
frameworks/av/include/media/stagefright/MediaCodecSource.h:57:22: error: 'android::MediaCodecSource::pause' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
    virtual status_t pause(MetaData *params = NULL);
                     ^
frameworks/av/include/media/stagefright/MediaSource.h:65:22: note: hidden overloaded virtual function 'android::MediaSource::pause' declared here: different number of parameters (0 vs 1)
    virtual status_t pause() {
                     ^
Replace the default parameter with a separate method, and have the
overloaded method call the parameter method.

Bug: 31751828
Test: builds
Change-Id: I10978d1e9987805a25cc27e1633bead83ac4e557
(cherry picked from commit 4f7427b3efff1da81aa42030acdc779227e6c433)