Update patch set 1
Patch Set 1:

Breaks the build on non qcom hardware.

frameworks/av/media/libstagefright/OMXCodec.cpp:696:13: error: 'ExtendedCodec' has not been declared

Patch-set: 1
Reviewer: Thomas Wendt <5678@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Verified=0