Revert "Update drm hal to find drm@1.1 factories"
This reverts commit a3c77911df570d4378ae4869d1060915001f0eba.

Reason for revert: build cop here. The original CL broke build git_master / walleye_asan, hence I'm reverting.

https://android-build.googleplex.com/builds/submitted/4597721/walleye_asan-userdebug/latest/view/logs/build_error.log

In file included from vendor/google/tools/security/fuzzers/libFuzzer/ICrypto_fuzzer/ICrypto_fuzzer.cpp:24:
frameworks/av/include/media/CryptoHal.h:23:10: fatal error: 'android/hardware/drm/1.1/ICryptoFactory.h' file not found

Change-Id: I185d5310cadb9990b864d71e42bba94f4740160c